apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp.q6
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: examdemoq6
          image: mohammadhani14/examdemo:v1